stress test script improvement

diff --git a/template/sh_stress b/template/sh_stress
--- a/template/sh_stress
+++ b/template/sh_stress
@@ -22,12 +22,22 @@ while : ; do
             break
         fi
     fi
-    echo -e "\e[34m./${3:-brute.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/expected.txt\e[39m"
-    if ! ./${3:-brute.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/expected.txt ; then
-        echo -e "\e[31mbrute runtime error\e[39m"
-        echo -e "\e[33minput:\e[39m"
-        cat /mnt/tmpfs/input.txt
-        break
+    if [ -f "brute" ]; then
+        echo -e "\e[34m./${2:-brute} < /mnt/tmpfs/input.txt > /mnt/tmpfs/expected.txt\e[39m"
+        if ! ./${2:-brute} < /mnt/tmpfs/input.txt > /mnt/tmpfs/expected.txt ; then
+            echo -e "\e[31mbrute runtime error\e[39m"
+            echo -e "\e[33minput:\e[39m"
+            cat /mnt/tmpfs/input.txt
+            break
+        fi
+    else
+        echo -e "\e[34m./${3:-brute.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/expected.txt\e[39m"
+        if ! ./${3:-brute.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/expected.txt ; then
+            echo -e "\e[31mbrute runtime error\e[39m"
+            echo -e "\e[33minput:\e[39m"
+            cat /mnt/tmpfs/input.txt
+            break
+        fi
     fi
     if ! cmp --silent /mnt/tmpfs/output.txt /mnt/tmpfs/expected.txt ; then
         echo -e "\e[31mtest failed\e[39m"
