template improvements

diff --git a/template/sh_stress b/template/sh_stress
--- a/template/sh_stress
+++ b/template/sh_stress
@@ -7,13 +7,28 @@ while : ; do
     ./${1:-gen.py} $tc > /mnt/tmpfs/input.txt
     if [ -f "solution" ]; then
         echo -e "\e[34m./${2:-solution} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt\e[39m"
-        ./${2:-solution} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt
+        if ! ./${2:-solution} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt ; then
+            echo -e "\e[31msolution runtime error\e[39m"
+            echo -e "\e[33minput:\e[39m"
+            cat /mnt/tmpfs/input.txt
+            break
+        fi
     else
         echo -e "\e[34m./${2:-solution.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt\e[39m"
-        ./${2:-solution.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt
+        if ! ./${2:-solution.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt ; then
+            echo -e "\e[31msolution runtime error\e[39m"
+            echo -e "\e[33minput:\e[39m"
+            cat /mnt/tmpfs/input.txt
+            break
+        fi
     fi
     echo -e "\e[34m./${3:-brute.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/expected.txt\e[39m"
-    ./${3:-brute.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/expected.txt
+    if ! ./${3:-brute.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/expected.txt ; then
+        echo -e "\e[31mbrute runtime error\e[39m"
+        echo -e "\e[33minput:\e[39m"
+        cat /mnt/tmpfs/input.txt
+        break
+    fi
     if ! cmp --silent /mnt/tmpfs/output.txt /mnt/tmpfs/expected.txt ; then
         echo -e "\e[31mtest failed\e[39m"
         echo -e "\e[33minput:\e[39m"
@@ -22,6 +37,9 @@ while : ; do
         cat /mnt/tmpfs/output.txt
         echo -e "\e[33mexpected:\e[39m"
         cat /mnt/tmpfs/expected.txt
+        cp /mnt/tmpfs/input.txt ./input.txt
+        cp /mnt/tmpfs/output.txt ./output.txt
+        cp /mnt/tmpfs/expected.txt ./expected.txt
         break
     fi
     echo -e "\e[32m$((tc++)) test cases passed\e[39m"
diff --git a/template/sh_stresschecker b/template/sh_stresschecker
--- a/template/sh_stresschecker
+++ b/template/sh_stresschecker
@@ -7,12 +7,25 @@ while : ; do
     ./${1:-gen.py} $tc > /mnt/tmpfs/input.txt
     if [ -f "solution" ]; then 
         echo -e "\e[34m./${2:-solution} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt\e[39m"
-        ./${2:-solution} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt
+        if ! ./${2:-solution} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt ; then
+            echo -e "\e[31msolution runtime error\e[39m"
+            echo -e "\e[33minput:\e[39m"
+            cat /mnt/tmpfs/input.txt
+            break
+        fi
     else
         echo -e "\e[34m./${2:-solution.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt\e[39m"
-        ./${2:-solution.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt
+        if ! ./${2:-solution.py} < /mnt/tmpfs/input.txt > /mnt/tmpfs/output.txt ; then
+            echo -e "\e[31msolution runtime error\e[39m"
+            echo -e "\e[33minput:\e[39m"
+            cat /mnt/tmpfs/input.txt
+            break
+        fi
     fi
     echo -e "\e[34m./${3:-checker.py} < /mnt/tmpfs/output.txt\e[39m"
-    ./${3:-checker.py} < /mnt/tmpfs/output.txt
+    if ! ./${3:-checker.py} < /mnt/tmpfs/output.txt ; then
+        cp /mnt/tmpfs/input.txt ./input.txt
+        break
+    fi
     echo -e "\e[32m$((tc++)) test cases passed\e[39m"
 done
